inherit_from: .rubocop_todo.yml

# Style Choices

Metrics/LineLength:
  Max: 100

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': ~~

# Rejection of nonsensical Rules and things I don't care about

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
