inherit_from: .rubocop_todo.yml

# Style Choices

Metrics/LineLength:
  Max: 100

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys


# Rejection of nonsensical Rules

Lint/AmbiguousRegexpLiteral:
  Enabled:
    false
