language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
  - 2.4.0
before_install: gem install bundler -v 1.10.6
install: bundle install --jobs=3 --retry=3 --without development
